name: Backend Continuous Integration

on: 
  push:
    branches:
      - main
    
  # Automatic trigger on pull requests that are closed to the main branch
  pull_request:
    branches:
      - main
    paths:
      - 'starter/backend/**'
  
  # Manual trigger using the workflow_dispatch event
  workflow_dispatch:

defaults:
  run:
    working-directory: ./starter/backend

jobs:
  lint:
    name: 'Lint'
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: install pip env
        run: |
          pip install pipenv --user
          pip install flake8

      - name: Run linting
        run: pipenv run lint
  test:
    name: 'Test'
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'
      
      - name: install pip env
        run: pip install pipenv --user
      
      - name: Install dependencies
        run: pipenv install
      
      - name: Run tests
        run: pipenv run test

  build:
    name: 'Build'
    runs-on: ubuntu-latest
    needs: [lint, test]

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: install pip env
        run: pip install pipenv --user

      - name: Install dependencies
        run: docker build --tag mp-backend:latest .